```{r}
library(Rfacebook)
library(tidyverse)
token <- "EAACEdEose0cBAJQmsLbsrttP0LCU4e3VDSk4PdTIzpKIeyyrSb8pLqA6FBN92RPUtFVe3YSZAD8Eqrb4smXZBVyoDMCSbWJEjEMZCohhOh8pwr54QXWvyzdZCn8eDnZBAmlUeNtXDNQetZBtyVbOwXYlqdxWHXH2ZCgn0YHOZBzuOHYev3AWKjKaTZAZCvtIh99CrRmFiR8lZCMPwZDZD"
```

```{r, echo=TRUE}
#卡提諾 最近50筆資料
pages_crazyck101_o <- getPage(page="crazyck101", token = token, n=50)  
pages_crazyck101 <- pages_crazyck101_o[,c(-1, -7)]
pages_crazyck101
write.csv(pages_crazyck101, file = "posts_crazyck101.csv")
```

```{r, echo=TRUE}
#卡提諾 按讚留言分享數
df_crazyck101 <- pages_crazyck101 %>%
  group_by(type) %>%
  summarise(likes=mean(likes_count), comments=mean(comments_count), shares=mean(shares_count)) %>%
  arrange(desc(shares))
df_crazyck101
```

```{r, echo=TRUE}
#卡提諾 最多分享的貼文
library(stringr)
summary_crazyck101 <- pages_crazyck101[which.max(pages_crazyck101$shares_count),]
str_split(summary_crazyck101$message, "\n")
```

```{r, echo=TRUE}
#卡提諾 最多分享的貼文 網友留言內容
post_crazyck101 <- getPost(pages_crazyck101_o$id[37], token=token, n.comments=20, likes=FALSE)
comments_crazyck101 <- post_crazyck101$comments
comments_crazyck101[,3]
```
